Main part game 012man
23350406/Python pull request #18
Opened 2024-12-18 23:32 UTC by boris012man

2024-12-19 12:33 UTC, frozzzen123 requested changes
Проверил создание классов

2024-12-19 12:33 UTC, frozzzen123 commented on Python/include/GameInfo.h
> +class Player
Вынести в PlayerClass.h

2024-12-19 12:33 UTC, frozzzen123 commented on Python/include/GameInfo.h
> +class Cell
Вынести в CellClass.h

2024-12-19 12:33 UTC, frozzzen123 commented on Python/include/GameInfo.h
> +class Field
Вынести в FieldClass.h

2024-12-19 12:33 UTC, frozzzen123 commented on Python/include/GameInfo.h
> +class Snake
Вынести в SnakeClass.h

2024-12-19 12:33 UTC, frozzzen123 commented on Python/include/GameInfo.h
> +    vector<Player> _team;
TODO: _team -> _players

2024-12-19 12:33 UTC, frozzzen123 commented on Python/include/GameInfo.h
> +    int _countPlayers;
_countPlayers -> _countHumans

2024-12-19 12:33 UTC, frozzzen123 commented on Python/include/GameInfo.h
> +    void SetTeam(vector<Player> team);
SetTeam -> SetPlayers

2024-12-19 12:33 UTC, frozzzen123 commented on Python/include/GameInfo.h
> +	void SetLine(vector<Cell*> line);
SetLine -> SetField

2024-12-19 12:33 UTC, frozzzen123 commented on Python/include/GameInfo.h
> +    vector<Cell*> _line;
_line -> _field

2024-12-19 12:33 UTC, frozzzen123 commented on Python/include/GameInfo.h
> +	void SetDirection(string direction);
Добавить функции для удаления символа с начала строки и добавления символа в конец строки (можно использовать очередь или дек)

2024-12-19 12:33 UTC, frozzzen123 commented on Python/include/PlayerClass.h
> +char Player::GetMove(string move)
move -> moveName

2024-12-19 12:33 UTC, frozzzen123 commented on Python/include/GameInfo.h
> +    string GetColor();
string -> sf::Color

2024-12-19 12:33 UTC, frozzzen123 commented on Python/include/GameInfo.h
> +	void SetColor(string color);
string -> sf::Color

2024-12-20 14:57 UTC, boris012man commented
Обновил файлы. Вместо объявлений внутри классовых файлов добавил их в funcionsFullProject; 
Методы будут реализованы Эдгаром

2024-12-20 15:02 UTC, boris012man commented
технические шоколадки, пока не работает

2024-12-21 01:25 UTC, boris012man commented on Python/include/GameInfo.h
> +    vector<Player> _team;
Сделано

2024-12-21 01:27 UTC, boris012man commented
Реализовал методы движения змейки

2024-12-21 04:19 UTC, frozzzen123 commented
Проверил исправление ошибок

2024-12-21 15:19 UTC, 23350406 commented
удалить папки CMake и build. Разрешить конфликты

2024-12-21 17:32 UTC, boris012man commented
Убрал лишние файлы

2024-12-22 07:27 UTC, frozzzen123 approved these changes

2024-12-22 07:48 UTC, merged